# -*- coding: utf-8 -*-
"""Making WordFile With Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dw0q9xTMpsMndvYpwqR4ynbPmmkfNKsx
"""

# pip install python-docx

from docx import Document

doc = Document()

doc.add_heading("Interview Questions for wordpress Developer (1 Year Experience)",0)

categories = {
    "General & Background": [
        "Can you introduce yourself and explain your WordPress development experience?",
        "What motivated you to apply for a Full Stack role at Griphic?",
        "How do you think your WordPress experience prepares you for full-stack development?",
        "Have you worked on projects involving teamwork across design and development teams?",
        "What’s your approach to learning new technologies quickly?"
    ],
    "Frontend Development (React, Angular, HTML/CSS/JS)": [
        "What is the difference between React and Angular?",
        "How would you compare using WordPress themes vs. React components?",
        "Can you explain the Virtual DOM in React?",
        "How do you handle state management in React?",
        "Have you used TailwindCSS, Bootstrap, or Material UI? Which do you prefer?"
    ],
    "3D & Web Rendering (Three.js, WebGL, Visualization)": [
        "What do you know about Three.js?",
        "Can you explain how WebGL works?",
        "Have you worked with 3D content on the web (e.g., embedding 3D models in WordPress)?",
        "How would you optimize a 3D scene for performance?",
        "How would you integrate a 3D interactive model into a React or WordPress project?"
    ],
    "Backend Development (Node.js, Python, APIs)": [
        "How is Node.js different from PHP (used in WordPress)?",
        "Can you explain how Express.js works?",
        "How do REST APIs work, and have you used them in WordPress?",
        "How would you build an API endpoint in Node.js?",
        "What’s the difference between REST and GraphQL?"
    ],
    "WebSockets & Real-time Systems": [
        "What are WebSockets and why are they useful?",
        "Have you worked with AJAX in WordPress? How does it compare to WebSockets?",
        "Can you describe a use case where real-time communication would be needed?",
        "How would you debug issues with WebSockets not sending messages?",
        "How would you scale a chat or real-time app?"
    ],
    "Databases (MySQL, MongoDB)": [
        "What experience do you have with MySQL from WordPress?",
        "Can you explain the difference between relational (MySQL) and non-relational (MongoDB) databases?",
        "How do you optimize database queries?",
        "What is indexing in databases?",
        "How do you perform a database migration?"
    ],
    "Cloud (AWS, GCP, Azure)": [
        "Have you hosted WordPress on cloud platforms?",
        "What’s the difference between shared hosting and cloud hosting?",
        "What are AWS EC2 and S3 used for?",
        "How would you deploy a Node.js app on AWS?",
        "Have you used any CI/CD pipelines?"
    ],
    "Security & Optimization": [
        "What are common security risks in WordPress?",
        "How would you secure a Node.js/React application?",
        "What is XSS and how do you prevent it?",
        "What is CSRF and how do you prevent it?",
        "How do you optimize frontend performance?"
    ],
    "Collaboration & Workflow": [
        "How do you use Git in your workflow?",
        "How do you manage conflicts when working in a team project?",
        "How do you write documentation for your code?",
        "How do you test and debug your applications?",
        "How do you handle client requests for new features vs bug fixes?"
    ],
    "Problem-Solving & Scenario-Based": [
        "You are asked to integrate a 3D model into a company’s landing page. How would you approach it?",
        "If a website is loading too slowly, how would you find the root cause?",
        "How would you migrate an existing WordPress site to a React + Node.js stack?",
        "A WebSocket-based feature keeps disconnecting. How would you debug it?",
        "How would you design an app that supports real-time collaboration (like Google Docs)?"
    ],
    "Personal & Growth": [
        "Which technology are you most excited to learn next (React, Node.js, or Three.js)?",
        "Tell me about a challenging bug you fixed in WordPress.",
        "How do you balance learning new tech with delivering current projects?",
        "Why do you want to shift from WordPress to a full-stack role?",
        "Where do you see yourself in the next 2–3 years?"
    ]
}

for category, questions in categories.items():
    doc.add_heading(category, level=1)
    for i, q in enumerate(questions, 1):
        doc.add_paragraph(f"{i}. {q}")

file_path = "/home/divyanshu/Documents/FullStack_Developer_Interview_Questions_for_WP_Dev.docx"

doc.save(file_path)

file_path

